server:
  port: 8080
  address: 0.0.0.0  # <--- Forces Spring Boot to listen to traffic from all network bridges

spring:
  application:
    name: devsync-server

  datasource:
    url: jdbc:postgresql://localhost:5432/devsync
    username: devsync
    password: devsync123
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: 172.24.104.9
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: mappings
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.type.descriptor.sql: OFF

jwt:
  secret: "DevSyncSuperSecretSecureSigningKey2026EnterpriseEdition"